name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Copy source files
        run: |
          mkdir dist
          cp src/* ./dist/ -rf

      - name: Set custom domain
        run: |
          echo "taiprogramer.xyz" > CNAME
          mv ./CNAME ./dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
